services:
    importexport.content.field.value.transformer.ezstring:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\GenericFieldValueTransformer
        arguments:
            $propertyName: 'value.text'
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ezstring' }

    importexport.content.field.value.transformer.ezrichtext:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\RichtextFieldValueTransformer
        arguments:
            $richTextOutputConverter: '@ibexa.richtext.converter.output.xhtml5'
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ezrichtext' }

    importexport.content.field.value.transformer.ezdate:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\DateFieldValueTransformer
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ezdate' }

    importexport.content.field.value.transformer.ezdatetime:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\DateTimeFieldValueTransformer
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ezdatetime' }

    importexport.content.field.value.transformer.ibexa_taxonomy_entry_assignment:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\TaxonomyFieldValueTransformer
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ibexa_taxonomy_entry_assignment' }

    importexport.content.field.value.transformer.ezselection:
        class: AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\Content\Field\ValueTransformer\SelectionFieldValueTransformer
        tags:
            - { name: 'importexport.content.field.value.transformer', type: 'ezselection' }
