services:
    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository:
        arguments:
            $entityManager: '@ibexa.doctrine.orm.entity_manager'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobService:
        arguments:
            $jobRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRepository'
            $jobRunner: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner'

    AlmaviaCX\Bundle\IbexaImportExport\Job\JobRunner:
        arguments:
            $workflowExecutor: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor'
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'
            $eventDispatcher: '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'

    AlmaviaCX\Bundle\IbexaImportExport\Job\Form\Type\JobCreateType:
        arguments:
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'
        tags:
            - { name: form.type, alias: AlmaviaCX\Bundle\IbexaImportExport\Job\Form\Type\JobCreateType }

    AlmaviaCX\Bundle\IbexaImportExport\Job\Form\JobCreateFlow:
        parent: craue.form.flow

