services:
    AlmaviaCX\Bundle\IbexaImportExportBundle\Controller\Admin\JobController:
        autowire: true
        arguments:
            $formFactory: '@form.factory'
            $notificationHandler: '@Ibexa\AdminUi\Notification\TranslatableNotificationHandler'
            $jobCreateFlow: '@AlmaviaCX\Bundle\IbexaImportExport\Job\Form\JobCreateFlow'
            $jobService: '@AlmaviaCX\Bundle\IbexaImportExport\Job\JobService'
            $eventDispatcher: '@event_dispatcher'
        tags:
            - controller.service_arguments

    AlmaviaCX\Bundle\IbexaImportExportBundle\Controller\Admin\WriterController:
        autowire: true
        arguments:
            $twig: '@twig'
            $componentRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Component\ComponentRegistry'
            $filesystem: '@filesystem'
        tags:
            - controller.service_arguments

    AlmaviaCX\Bundle\IbexaImportExport\AdminUi\Menu\JobCreateRightSidebarBuilder:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $factory: '@Ibexa\AdminUi\Menu\MenuItemFactory'
            $translator: '@translator'
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: almaviacx.import_export.menu.job_create.sidebar_right }

    AlmaviaCX\Bundle\IbexaImportExport\Resolver\FilepathResolver:
        arguments:
            $parameterBag: '@parameter_bag'

    AlmaviaCX\Bundle\IbexaImportExport\Event\Subscriber\RemoveWrittenFilesEventSubscriber:
        arguments:
            $fileHandler: '@AlmaviaCX\Bundle\IbexaImportExport\File\FileHandler'
        tags:
            - kernel.event_subscriber

    AlmaviaCX\Bundle\IbexaImportExport\Event\Subscriber\PostJobCreateFormSubmitEventSubscriber:
        arguments:
            $fileHandler: '@AlmaviaCX\Bundle\IbexaImportExport\File\FileHandler'
        tags:
            - kernel.event_subscriber

    almaviacx.importexport.file_prefixer:
        class: League\Flysystem\PathPrefixer
        arguments:
            $prefix: 'import_export'

    AlmaviaCX\Bundle\IbexaImportExport\File\FileHandler:
        arguments:
            $innerAdapter: '@ibexa.core.io.flysystem.adapter.site_access_aware'
            $prefixer: '@almaviacx.importexport.file_prefixer'
            $filepathResolver: '@AlmaviaCX\Bundle\IbexaImportExport\Resolver\FilepathResolver'

    AlmaviaCX\Bundle\IbexaImportExport\AdminUi\Menu\Event\MenuListener:
        tags:
            - { name: kernel.event_subscriber }