services:
    AlmaviaCX\Bundle\IbexaImportExport\Reader\Ibexa\ContentList\IbexaContentListReader:
        arguments:
            $searchService: '@Ibexa\Contracts\Core\Repository\SearchService'
            $valueAccessorBuilder: '@AlmaviaCX\Bundle\IbexaImportExport\Accessor\Ibexa\ValueAccessorBuilder'
        tags:
            - almaviacx.importexport.reader


    AlmaviaCX\Bundle\IbexaImportExport\Reader\Csv\CsvReader:
        tags:
            - almaviacx.importexport.reader

    AlmaviaCX\Bundle\IbexaImportExport\Reader\Csv\CsvReaderOptionsFormType:
        tags:
            - { name: form.type, alias: CsvReaderOptionsFormType }

    AlmaviaCX\Bundle\IbexaImportExport\Reader\Ibexa\ContentList\IbexaContentListReaderOptionsFormType:
        tags:
            - { name: form.type, alias: IbexaContentListReaderOptionsFormType }
