services:
    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowConfigurationRepository:
        arguments:
            $entityManager: '@ibexa.doctrine.orm.entity_manager'

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowExecutor:
        arguments:
            $componentRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Component\ComponentRegistry'

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry:
        arguments:
            $typeContainer: !abstract defined in AlmaviaCX\Bundle\IbexaImportExportBundle\DependencyInjection\CompilerPass\WorkflowPass
            $typesList: !abstract defined in AlmaviaCX\Bundle\IbexaImportExportBundle\DependencyInjection\CompilerPass\WorkflowPass
            $configurableWorkflowFactory: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\ConfigurableWorkflowFactory'
            $workflowConfigurationRepository: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowConfigurationRepository'


    AlmaviaCX\Bundle\IbexaImportExport\Workflow\ConfigurableWorkflowFactory:

    AlmaviaCX\Bundle\IbexaImportExport\Workflow\Form\Type\WorkflowProcessConfigurationFormType:
        arguments:
            $workflowRegistry: '@AlmaviaCX\Bundle\IbexaImportExport\Workflow\WorkflowRegistry'
        tags:
            - { name: form.type, alias: WorkflowProcessConfigurationFormType }
