services:
    AlmaviaCX\Bundle\IbexaImportExport\Writer\Csv\CsvWriter:
        arguments:
            $fileHandler: '@AlmaviaCX\Bundle\IbexaImportExport\File\FileHandler'
        tags:
            - { name: almaviacx.importexport.writer }

    AlmaviaCX\Bundle\IbexaImportExport\Writer\Stream\StreamWriterOptionsFormType:
        arguments:
            $filepathResolver: '@AlmaviaCX\Bundle\IbexaImportExport\Resolver\FilepathResolver'
        tags:
            - { name: form.type, alias: StreamWriterOptionsFormType }
